module.exports = [
  '<div class="plan free">',
    '<div class="icon">',
      '<img src="/images/newsite/plans/free.png" width="148" height="150">',
    '</div>',
    '<div class="desc">',
      '<div class="price">',
        '$<span class="amount">0</span> <span class="per">/ month</span>',
      '</div>',
      '<div class="title">',
        'free plan',
      '</div>',
      '',
      'Great for students, casual cross-browser testing, and product',
      'evaluation.',
      '',
      '<div class="features">'
        '5-minute sessions',
      '</div>',
    '</div>',
    '<div class="more">',
      '<ul>',
        '<li>Use browserling for 5 minutes at a time as much as you like.</li>',
        '<li>Sometimes you'll need to wait in a queue if the site is busy.</li>',
        '<li>Includes 30 <a href="http://testling.com">testling</a> minutes per month.</li>',
      '</ul>',
      '<div class="yours">You have this plan.</div>',
    '</div>',
  '</div>',
  '<input class="buy" type="button">'
  '<div class="back">',
    '<a href="#">back</a>',
  '</div>'
].join('\n')
